#!/bin/sh

for mini in "${@:2}"
do    
   out="$(basename $mini)"
   echo "; ModuleID = '$out'" > ${mini%.*}.ll
   echo "source_filename = \"$out\"" >> ${mini%.*}.ll
   echo "target datalayout = \"e-m:o-i64:64-f80:128-n8:16:32:64-S128\"" >> ${mini%.*}.ll
   echo "target triple = \"x86_64-apple-macosx10.15.0\"" >> ${mini%.*}.ll
   racket compile.rkt "$1" $(java -jar ../mile1/given/MiniCompiler.jar $mini) >> ${mini%.*}.ll
done
