#lang racket

(require json)
(require rackunit)
(require "compiler.rkt")
(require "definitions.rkt")

;; (UNTYPED) RACKET TEST CASES

;; test cases for parse

;; 1.mini
(check-equal?
 (parse
  #hasheq((declarations . (#hasheq((id . "i") (line . 13) (type . "int"))
                           #hasheq((id . "j") (line . 13) (type . "int"))
                           #hasheq((id . "k") (line . 13) (type . "int"))
                           #hasheq((id . "b") (line . 14) (type . "B"))
                           #hasheq((id . "bb") (line . 14) (type . "B"))
                           #hasheq((id . "bbb") (line . 14) (type . "B"))
                           #hasheq((id . "bob") (line . 15) (type . "bool"))))
          (functions . (#hasheq((body . (#hasheq((exp . #hasheq((exp . "dot")
                                                                (id . "a")
                                                                (left . #hasheq((exp . "dot")
                                                                                (id . "a")
                                                                                (left . #hasheq((exp . "dot")
                                                                                                (id . "a")
                                                                                                (left . #hasheq((exp . "dot")
                                                                                                                (id . "a")
                                                                                                                (left . #hasheq((exp . "id")
                                                                                                                                (id . "b")
                                                                                                                                (line . 20)))
                                                                                                                (line . 20)))
                                                                                                (line . 20)))
                                                                                (line . 20)))
                                                                (line . 20)))
                                                 (line . 20)
                                                 (stmt . "return"))))
                                (declarations . (#hasheq((id . "f") (line . 19) (type . "int"))
                                                 #hasheq((id . "l") (line . 19) (type . "int"))
                                                 #hasheq((id . "k") (line . 19) (type . "int"))))
                                (id . "f")
                                (line . 17)
                                (parameters . (#hasheq((id . "i") (line . 17) (type . "int"))
                                               #hasheq((id . "j") (line . 17) (type . "B"))))
                                (return_type . "A"))
                        #hasheq((body . (#hasheq((else . #hasheq((list . (#hasheq((exp . #hasheq((exp . "binary")
                                                                                                 (lft . #hasheq((exp . "id")
                                                                                                                (id . "n")
                                                                                                                (line . 31)))
                                                                                                 (line . 31)
                                                                                                 (operator . "*")
                                                                                                 (rht . #hasheq((args . (#hasheq((exp . "binary")
                                                                                                                                 (lft . #hasheq((exp . "id")
                                                                                                                                                (id . "n")
                                                                                                                                                (line . 31)))
                                                                                                                                 (line . 31)
                                                                                                                                 (operator . "-")
                                                                                                                                 (rht . #hasheq((exp . "num")
                                                                                                                                                (line . 31)
                                                                                                                                                (value . "1"))))))
                                                                                                                (exp . "invocation")
                                                                                                                (id . "foo")
                                                                                                                (line . 31)))))
                                                                                  (line . 31)
                                                                                  (stmt . "return"))))
                                                                 (stmt . "block")))
                                                 (guard . #hasheq((exp . "binary")
                                                                  (lft . #hasheq((exp . "id")
                                                                                 (id . "n")
                                                                                 (line . 25)))
                                                                  (line . 25)
                                                                  (operator . "<=")
                                                                  (rht . #hasheq((exp . "num")
                                                                                 (line . 25)
                                                                                 (value . "0")))))
                                                 (line . 25)
                                                 (stmt . "if")
                                                 (then . #hasheq((list . (#hasheq((exp . #hasheq((exp . "num")
                                                                                                 (line . 27)
                                                                                                 (value . "1")))
                                                                                  (line . 27)
                                                                                  (stmt . "return"))))
                                                                 (stmt . "block"))))))
                                (declarations . ())
                                (id . "foo")
                                (line . 23)
                                (parameters . (#hasheq((id . "n") (line . 23) (type . "int"))))
                                (return_type . "int"))
                        #hasheq((body . (#hasheq((exp . #hasheq((exp . "num")
                                                                (line . 38)
                                                                (value . "3")))
                                                 (line . 38)
                                                 (stmt . "return"))))
                                (declarations . (#hasheq((id . "g") (line . 37) (type . "int"))
                                                 #hasheq((id . "m") (line . 37) (type . "int"))
                                                 #hasheq((id . "k") (line . 37) (type . "int"))))
                                (id . "g")
                                (line . 35)
                                (parameters . (#hasheq((id . "i") (line . 35) (type . "int"))
                                               #hasheq((id . "j") (line . 35) (type . "B"))))
                                (return_type . "int"))
                        #hasheq((body . (#hasheq((list . (#hasheq((line . 48)
                                                                  (source . #hasheq((exp . "num")
                                                                                    (line . 48)
                                                                                    (value . "2")))
                                                                  (stmt . "assign")
                                                                  (target . #hasheq((id . "i") (line . 48))))
                                                          #hasheq((guard . #hasheq((exp . "binary")
                                                                                   (lft . #hasheq((exp . "id")
                                                                                                  (id . "i")
                                                                                                  (line . 49)))
                                                                                   (line . 49)
                                                                                   (operator . "<")
                                                                                   (rht . #hasheq((args . (#hasheq((exp . "num")
                                                                                                                   (line . 49)
                                                                                                                   (value . "1"))
                                                                                                           #hasheq((exp . "null")
                                                                                                                   (line . 49))))
                                                                                                  (exp . "invocation")
                                                                                                  (id . "g")
                                                                                                  (line . 49)))))
                                                                  (line . 49)
                                                                  (stmt . "if")
                                                                  (then . #hasheq((list . (#hasheq((endl . #f)
                                                                                                   (exp . #hasheq((exp . "num")
                                                                                                                  (line . 51)
                                                                                                                  (value . "1")))
                                                                                                   (line . 51)
                                                                                                   (stmt . "print"))))
                                                                                  (stmt . "block"))))
                                                          #hasheq((else . #hasheq((list . (#hasheq((endl . #t)
                                                                                                   (exp . #hasheq((exp . "num")
                                                                                                                  (line . 60)
                                                                                                                  (value . "3")))
                                                                                                   (line . 60)
                                                                                                   (stmt . "print"))))
                                                                                  (stmt . "block")))
                                                                  (guard . #hasheq((exp . "binary")
                                                                                   (lft . #hasheq((exp . "id")
                                                                                                  (id . "i")
                                                                                                  (line . 54)))
                                                                                   (line . 54)
                                                                                   (operator . ">")
                                                                                   (rht . #hasheq((args . (#hasheq((exp . "num")
                                                                                                                   (line . 54)
                                                                                                                   (value . "1"))
                                                                                                           #hasheq((exp . "null")
                                                                                                                   (line . 54))))
                                                                                                  (exp . "invocation")
                                                                                                  (id . "g")
                                                                                                  (line . 54)))))
                                                                  (line . 54)
                                                                  (stmt . "if")
                                                                  (then . #hasheq((list . (#hasheq((endl . #f)
                                                                                                   (exp . #hasheq((exp . "num")
                                                                                                                  (line . 56)
                                                                                                                  (value . "1")))
                                                                                                   (line . 56)
                                                                                                   (stmt . "print"))))
                                                                                  (stmt . "block"))))
                                                          #hasheq((body . #hasheq((list . (#hasheq((endl . #f)
                                                                                                   (exp . #hasheq((exp . "num")
                                                                                                                  (line . 64)
                                                                                                                  (value . "7")))
                                                                                                   (line . 64)
                                                                                                   (stmt . "print"))))
                                                                                  (stmt . "block")))
                                                                  (guard . #hasheq((exp . "true")
                                                                                   (line . 62)))
                                                                  (line . 62)
                                                                  (stmt . "while"))
                                                          #hasheq((args . (#hasheq((args . (#hasheq((exp . "num")
                                                                                                    (line . 66)
                                                                                                    (value . "1"))
                                                                                            #hasheq((exp . "new")
                                                                                                    (id . "B")
                                                                                                    (line . 66))))
                                                                                   (exp . "invocation")
                                                                                   (id . "g")
                                                                                   (line . 66))
                                                                           #hasheq((exp . "new")
                                                                                   (id . "B")
                                                                                   (line . 66))))
                                                                  (id . "f")
                                                                  (line . 66)
                                                                  (stmt . "invocation"))
                                                          #hasheq((endl . #t)
                                                                  (exp . #hasheq((exp . "dot")
                                                                                 (id . "i")
                                                                                 (left . #hasheq((args . (#hasheq((args . (#hasheq((exp . "num")
                                                                                                                                   (line . 67)
                                                                                                                                   (value . "1"))
                                                                                                                           #hasheq((exp . "new")
                                                                                                                                   (id . "B")
                                                                                                                                   (line . 67))))
                                                                                                                  (exp . "invocation")
                                                                                                                  (id . "g")
                                                                                                                  (line . 67))
                                                                                                          #hasheq((exp . "new")
                                                                                                                  (id . "B")
                                                                                                                  (line . 67))))
                                                                                                 (exp . "invocation")
                                                                                                 (id . "f")
                                                                                                 (line . 67)))
                                                                                 (line . 67)))
                                                                  (line . 67)
                                                                  (stmt . "print"))))
                                                 (stmt . "block"))
                                         #hasheq((exp . #hasheq((exp . "num")
                                                                (line . 69)
                                                                (value . "0")))
                                                 (line . 69)
                                                 (stmt . "return"))))
                                (declarations . (#hasheq((id . "a")
                                                         (line . 43)
                                                         (type . "A"))
                                                 #hasheq((id . "i")
                                                         (line . 44)
                                                         (type . "int"))
                                                 #hasheq((id . "j")
                                                         (line . 44)
                                                         (type . "int"))
                                                 #hasheq((id . "k")
                                                         (line . 44)
                                                         (type . "int"))
                                                 #hasheq((id . "b")
                                                         (line . 45)
                                                         (type . "bool"))
                                                 #hasheq((id . "h")
                                                         (line . 46)
                                                         (type . "int"))))
                                (id . "main")
                                (line . 41)
                                (parameters . ())
                                (return_type . "int"))))
          (types . (#hasheq((fields . (#hasheq((id . "i")
                                               (line . 3)
                                               (type . "int"))
                                       #hasheq((id . "j1")
                                               (line . 4)
                                               (type . "int"))
                                       #hasheq((id . "b")
                                               (line . 5)
                                               (type . "bool"))
                                       #hasheq((id . "a")
                                               (line . 6)
                                               (type . "A"))))
                            (id . "A")
                            (line . 1))
                    #hasheq((fields . (#hasheq((id . "a")
                                               (line . 10)
                                               (type . "A"))))
                            (id . "B")
                            (line . 8))))))
 (Program
 (list
  (Struct
   'A
   (list
    (Declaration 'int 'i)
    (Declaration 'int 'j1)
    (Declaration 'bool 'b)
    (Declaration 'A 'a)))
  (Struct 'B (list (Declaration 'A 'a))))
 (list
  (Declaration 'int 'i)
  (Declaration 'int 'j)
  (Declaration 'int 'k)
  (Declaration 'B 'b)
  (Declaration 'B 'bb)
  (Declaration 'B 'bbb)
  (Declaration 'bool 'bob))
 (list
  (Function
   'f
   (list (Declaration 'int 'i) (Declaration 'B 'j))
   'A
   (list (Declaration 'int 'f) (Declaration 'int 'l) (Declaration 'int 'k))
   (list (Return (Selector (Selector (Selector (Selector 'b 'a) 'a) 'a) 'a))))
  (Function
   'foo
   (list (Declaration 'int 'n))
   'int
   '()
   (list
    (If-Else
     (Binary '<= 'n 0)
     (Block (list (Return 1)))
     (Block (list (Return (Binary '* 'n (Invocation 'foo (list (Binary '- 'n 1))))))))))
  (Function
   'g
   (list (Declaration 'int 'i) (Declaration 'B 'j))
   'int
   (list (Declaration 'int 'g) (Declaration 'int 'm) (Declaration 'int 'k))
   (list (Return 3)))
  (Function
   'main
   '()
   'int
   (list
    (Declaration 'A 'a)
    (Declaration 'int 'i)
    (Declaration 'int 'j)
    (Declaration 'int 'k)
    (Declaration 'bool 'b)
    (Declaration 'int 'h))
   (list
    (Block
     (list
      (Assignment 'i 2)
      (If (Binary '< 'i (Invocation 'g '(1 null))) (Block (list (Print 1 #f))))
      (If-Else
       (Binary '> 'i (Invocation 'g '(1 null)))
       (Block (list (Print 1 #f)))
       (Block (list (Print 3 #t))))
      (Loop #t (Block (list (Print 7 #f))))
      (Invocation 'f (list (Invocation 'g (list 1 (Allocation 'B))) (Allocation 'B)))
      (Print
       (Selector
        (Invocation 'f (list (Invocation 'g (list 1 (Allocation 'B))) (Allocation 'B)))
        'i)
       #t)))
    (Return 0))))))

;; contains all of the parse patterns that 1.mini is missing
(check-equal?
 (parse
  #hasheq((declarations
           .
           (#hasheq((id . "i") (line . 6) (type . "int"))
            #hasheq((id . "j") (line . 6) (type . "int"))))
          (functions
           .
           (#hasheq((body
                     .
                     (#hasheq((exp . #hasheq((exp . "id") (id . "a") (line . 11)))
                              (line . 11)
                              (stmt . "delete"))
                      #hasheq((line . 12)
                              (source . #hasheq((exp . "read") (line . 12)))
                              (stmt . "assign")
                              (target . #hasheq((id . "i") (line . 12))))
                      #hasheq((guard . #hasheq((exp . "false") (line . 13)))
                              (line . 13)
                              (stmt . "if")
                              (then
                               .
                               #hasheq((list
                                        .
                                        (#hasheq((line . 15)
                                                 (source
                                                  .
                                                  #hasheq((exp . "unary")
                                                          (line . 15)
                                                          (operand
                                                           .
                                                           #hasheq((exp . "num")
                                                                   (line . 15)
                                                                   (value . "5")))
                                                          (operator . "-")))
                                                 (stmt . "assign")
                                                 (target . #hasheq((id . "i") (line . 15))))))
                                       (stmt . "block"))))
                      #hasheq((line . 17) (stmt . "return"))))
                    (declarations . (#hasheq((id . "a") (line . 10) (type . "A"))))
                    (id . "f")
                    (line . 8)
                    (parameters
                     .
                     (#hasheq((id . "i") (line . 8) (type . "int"))
                      #hasheq((id . "j") (line . 8) (type . "int"))))
                    (return_type . "void"))
            #hasheq((body
                     .
                     (#hasheq((exp . #hasheq((exp . "num") (line . 22) (value . "4")))
                              (line . 22)
                              (stmt . "return"))))
                    (declarations . ())
                    (id . "main")
                    (line . 20)
                    (parameters . ())
                    (return_type . "int"))))
          (types
           .
           (#hasheq((fields . (#hasheq((id . "k") (line . 3) (type . "int"))))
                    (id . "A")
                    (line . 1))))))
 (Program
  (list (Struct 'A (list (Declaration 'int 'k))))
  (list (Declaration 'int 'i) (Declaration 'int 'j))
  (list
   (Function
    'f
    (list (Declaration 'int 'i) (Declaration 'int 'j))
    'void
    (list (Declaration 'A 'a))
    (list
     (Delete 'a)
     (Assignment 'i 'read)
     (If #f (Block (list (Assignment 'i (Unary '- 5)))))
     (Return-Void)))
   (Function 'main '() 'int '() (list (Return 4))))))(check-equal? (Program
  (list (Struct 'A (list (Declaration 'int 'k))))
  (list (Declaration 'int 'i) (Declaration 'int 'j))
  (list
   (Function
    'f
    (list (Declaration 'int 'i) (Declaration 'int 'j))
    'void
    (list (Declaration 'A 'a))
    (list
     (Delete 'a)
     (Assignment 'i 'read)
     (If #f (Block (list (Assignment 'i (Unary '- 5)))))
     (Return-Void)))
   (Function 'main '() 'int '() (list (Return 4)))))
              (Program
  (list (Struct 'A (list (Declaration 'int 'k))))
  (list (Declaration 'int 'i) (Declaration 'int 'j))
  (list
   (Function
    'f
    (list (Declaration 'int 'i) (Declaration 'int 'j))
    'void
    (list (Declaration 'A 'a))
    (list
     (Delete 'a)
     (Assignment 'i 'read)
     (If #f (Block (list (Assignment 'i (Unary '- 5)))))
     (Return-Void)))
   (Function 'main '() 'int '() (list (Return 4))))))